version: '3.8'

services:
  unzerapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Data Source=/app/UnzerDB.db"
    volumes:
      - ./Unzer/appsettings.yaml:/app/appsettings.yaml
      - ./Unzer/UnzerDB.db:/app/UnzerDB.db
